name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Eigen3
      run: sudo apt install -y libmpich-dev libeigen3-dev intel-oneapi-mkl
    - name: Install oneMKL
      run: |
        cd /tmp
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
        sudo apt update
	sudo apt install intel-oneapi-mkl
    - name: Configure
      run: |
        source /opt/intel/oneapi/mkl/latest/env/vars.sh
	cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release .
    - name: Build
      run: |
        source /opt/intel/oneapi/mkl/latest/env/vars.sh
	cmake --build . --config Release
    - name: Run unit tests
      run: |
        source /opt/intel/oneapi/mkl/latest/env/vars.sh
        ctest -V

  build_openmp:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Eigen3
      run: sudo apt install -y libmpich-dev libeigen3-dev
    - name: Install oneMKL
      run: |
        cd /tmp
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
        sudo apt update
	sudo apt install intel-oneapi-mkl
    - name: Configure
      run: |
        source /opt/intel/oneapi/mkl/latest/env/vars.sh
	cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DENABLE_OPENMP=on .
    - name: Build
      run: |
        source /opt/intel/oneapi/mkl/latest/env/vars.sh
	cmake --build . --config Release
    - name: Run unit tests
      run: |
        source /opt/intel/oneapi/mkl/latest/env/vars.sh
        ctest -V